<a href="https://colab.research.google.com/github/masterinfo/Machine_Learning_Pytorch_Colab/blob/main/Autograd_with_tensors_END.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Autograd with tensors

In [1]:
import torch

In [2]:
w = torch.randn(4,3,requires_grad=True)

In [3]:
w

tensor([[ 0.4106,  0.0422, -1.1644],
        [-0.3840,  0.2292,  0.3119],
        [ 0.9746,  0.5791,  0.3923],
        [-1.0751, -0.6646, -0.2843]], requires_grad=True)

In [4]:
w.requires_grad_(False)
w

tensor([[ 0.4106,  0.0422, -1.1644],
        [-0.3840,  0.2292,  0.3119],
        [ 0.9746,  0.5791,  0.3923],
        [-1.0751, -0.6646, -0.2843]])

In [5]:
w.requires_grad_(True)

tensor([[ 0.4106,  0.0422, -1.1644],
        [-0.3840,  0.2292,  0.3119],
        [ 0.9746,  0.5791,  0.3923],
        [-1.0751, -0.6646, -0.2843]], requires_grad=True)

In [6]:
y = torch.exp(w)
print(y)

tensor([[1.5077, 1.0431, 0.3121],
        [0.6811, 1.2576, 1.3660],
        [2.6500, 1.7845, 1.4804],
        [0.3413, 0.5145, 0.7525]], grad_fn=<ExpBackward0>)


In [7]:
print(y.grad_fn)

In [8]:
outp = y.mean()
print(outp)

tensor(1.1409, grad_fn=<MeanBackward0>)


In [12]:
print(w.grad)

tensor([[0.1256, 0.0869, 0.0260],
        [0.0568, 0.1048, 0.1138],
        [0.2208, 0.1487, 0.1234],
        [0.0284, 0.0429, 0.0627]])


In [13]:
outp.backward()

RuntimeError: ignored

In [11]:
print(w.grad)

tensor([[0.1256, 0.0869, 0.0260],
        [0.0568, 0.1048, 0.1138],
        [0.2208, 0.1487, 0.1234],
        [0.0284, 0.0429, 0.0627]])


In [14]:
print(w.detach())

tensor([[ 0.4106,  0.0422, -1.1644],
        [-0.3840,  0.2292,  0.3119],
        [ 0.9746,  0.5791,  0.3923],
        [-1.0751, -0.6646, -0.2843]])


In [ ]:
print(outp.requires_grad)

with torch.no_grad():
  outp = (w+y).mean()
  
print(outp.requires_grad)  

True
False
