<a href="https://colab.research.google.com/github/masterinfo/Machine_Learning_Pytorch_Colab/blob/main/scikitlearn_tuto_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.feature_extraction.text import CountVectorizer

# 1 - création et calcul du sac de mots
vectorizer = CountVectorizer()

# 2 - le corpus (3 documents)
corpus = ['un jour ici et la' ,  'demain mais pas ici' ,  'la la la lere']

# 3 – calcul du sac
bow = vectorizer.fit_transform(corpus)

In [21]:
print(vectorizer.get_feature_names_out())

['demain' 'et' 'ici' 'jour' 'la' 'lere' 'mais' 'pas' 'un']


In [22]:
print(vectorizer.get_params())

{'analyzer': 'word', 'binary': False, 'decode_error': 'strict', 'dtype': <class 'numpy.int64'>, 'encoding': 'utf-8', 'input': 'content', 'lowercase': True, 'max_df': 1.0, 'max_features': None, 'min_df': 1, 'ngram_range': (1, 1), 'preprocessor': None, 'stop_words': None, 'strip_accents': None, 'token_pattern': '(?u)\\b\\w\\w+\\b', 'tokenizer': None, 'vocabulary': None}


In [7]:
print(bow)

  (0, 8)	1
  (0, 3)	1
  (0, 2)	1
  (0, 1)	1
  (0, 4)	1
  (1, 2)	1
  (1, 0)	1
  (1, 6)	1
  (1, 7)	1
  (2, 4)	3
  (2, 5)	1


In [5]:
# ['un jour ici et là', 'demain mais pas ici', 'la la la lere']

# affichage de tous les mots du sac
print(vectorizer.get_feature_names_out())
print("***********************************")
# affichage brut du dénombrement des mots
print(bow.toarray())
print("***********************************")
# affichage dans un tableau 
import pandas as pd
pd.DataFrame(bow.toarray() , columns = vectorizer.get_feature_names_out())


['demain' 'et' 'ici' 'jour' 'la' 'lere' 'mais' 'pas' 'un']
***********************************
[[0 1 1 1 1 0 0 0 1]
 [1 0 1 0 0 0 1 1 0]
 [0 0 0 0 3 1 0 0 0]]
***********************************


demain  et  ici  jour  la  lere  mais  pas  un
0       0   1    1     1   1     0     0    0   1
1       1   0    1     0   0     0     1    1   0
2       0   0    0     0   3     1     0    0   0

le mot "la" apparait 3 FOIS DANS LE DOCUMENT 2