<a href="https://colab.research.google.com/github/masterinfo/Machine_Learning_Pytorch_Colab/blob/main/tenseur_grad.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**PyTorch Autograd **

La bibliothèque Autograd permet le calcul automatique de gradients d’une fonction par rapport à ses paramètres. Elle sert ainsi à effectuer facilement l’étape de backpropagation lors de l’entraînement d’un réseau de neurones. En effet, lorsqu’un tenseur est créé avec l’option require_grad = True, ceci signale à Autograd que chaque opération effectuée sur ce tenseur doit être gardée en mémoire.

In [3]:
## importer la bibliothèque PyTorch
import torch 
## définir un tenseur aléatoire
x = torch.randn(2, 2, requires_grad=True)
 
## effectuer une opération sur le tenseur : somme (xi**2)
print(x, x.dtype, x.shape)
 
## Attention l’opération doit retourner un scalaire pour que la fonction backward fonctionne
out = x.pow(2).sum() ## scalaire
print("tenseur out")
print(out, out.dtype, out.shape)
 
## étape de rétropropagation ou backward pour calculer les gradients de out par rapport à la variable x
out.backward() 
 
## Le gradient est stocké dans x.grad ; pour vérifier le résultat, on devrait avoir 2*x ( derivée de x^2 =2X )
print("tenseur gradient de x")
print(x.grad)
print("tenseur 2x")
print(2*x)

tensor([[-0.0076, -2.0898],
        [ 0.7299, -1.0437]], requires_grad=True) torch.float32 torch.Size([2, 2])
tenseur out
tensor(5.9894, grad_fn=<SumBackward0>) torch.float32 torch.Size([])
tenseur gradient de x
tensor([[-0.0152, -4.1796],
        [ 1.4597, -2.0874]])
tenseur 2x
tensor([[-0.0152, -4.1796],
        [ 1.4597, -2.0874]], grad_fn=<MulBackward0>)
