<a href="https://colab.research.google.com/github/masterinfo/Machine_Learning_Pytorch_Colab/blob/main/Using_Optimizers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Using optimizers

In [49]:
# Setting seeds to try and ensure we have the same results - this is not guaranteed across PyTorch releases.
import torch
torch.manual_seed(0)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

import numpy as np
np.random.seed(0)

Chargement des datas et normalisation

In [50]:
from torchvision import datasets, transforms
import torch.nn.functional as F
from torch import nn

mean, std = (0.5,), (0.5,)

# Create a transform and normalise data
transform = transforms.Compose([transforms.ToTensor(),
                                transforms.Normalize(mean, std)
                              ])

# Download FMNIST training dataset and load training data
trainset = datasets.FashionMNIST('~/.pytorch/FMNIST/', download=True, train=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=64, shuffle=True)

# Download FMNIST test dataset and load test data
testset = datasets.FashionMNIST('~/.pytorch/FMNIST/', download=True, train=False, transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=64, shuffle=False)

on ne se sers pas  de la classe

In [51]:
class FMNIST(nn.Module):
  def __init__(self):
    super().__init__()
    self.fc1 = nn.Linear(784, 128)
    self.fc2 = nn.Linear(128,64)
    self.fc3 = nn.Linear(64,10)
    
  def forward(self, x):
    x = x.view(x.shape[0], -1)
    
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = self.fc3(x)
    x = F.log_softmax(x, dim=1)
    
    return x
    
#model = FMNIST()   

creation du model a 3 couches  784 entrés ( le spixels) =>128 neurones premmiere couche avec un un fonction d'activation Relu )=> 64 neurones sur la seconde couche avec une fonction d'activation Relu => couche de sortie de 10 neurones avec logsoftmax multiclasse

In [52]:
model = nn.Sequential(nn.Linear(784, 128),
                      nn.ReLU(),
                      nn.Linear(128, 64),
                      nn.ReLU(),
                      nn.Linear(64, 10),
                      nn.LogSoftmax(dim=1))

In [53]:
images, labels = next(iter(trainloader))
images = images.view(images.shape[0], -1)

In [54]:
from torch import optim

criterion = nn.NLLLoss()
optimizer = optim.SGD(model.parameters(), lr=0.5)


premier passage juste pour comprendre l'effet de l'optimizer

In [55]:
output = model(images)
loss = criterion(output, labels)

print('Initial weights : ',model[0].weight)
print('Initial weights gradient : ',model[0].weight.grad)
loss.backward()
        

Initial weights :  Parameter containing:
tensor([[-0.0003,  0.0192, -0.0294,  ...,  0.0219,  0.0037,  0.0021],
        [-0.0198, -0.0150, -0.0104,  ..., -0.0203, -0.0060, -0.0299],
        [-0.0201,  0.0149, -0.0333,  ..., -0.0203,  0.0012,  0.0080],
        ...,
        [ 0.0018, -0.0295,  0.0085,  ..., -0.0037,  0.0036,  0.0300],
        [-0.0233, -0.0220, -0.0064,  ...,  0.0115, -0.0324, -0.0158],
        [ 0.0309,  0.0066,  0.0125,  ...,  0.0286,  0.0350, -0.0105]],
       requires_grad=True)
Initial weights gradient :  None


update de he weights

In [56]:
optimizer.step()

In [57]:
print('Initial weights : ',model[0].weight)
print('Initial weights gradient : ',model[0].weight.grad)

Initial weights :  Parameter containing:
tensor([[ 0.0012,  0.0206, -0.0279,  ...,  0.0234,  0.0052,  0.0035],
        [-0.0209, -0.0161, -0.0116,  ..., -0.0215, -0.0071, -0.0311],
        [-0.0202,  0.0148, -0.0334,  ..., -0.0204,  0.0011,  0.0079],
        ...,
        [ 0.0011, -0.0302,  0.0078,  ..., -0.0044,  0.0029,  0.0293],
        [-0.0243, -0.0231, -0.0075,  ...,  0.0105, -0.0334, -0.0168],
        [ 0.0290,  0.0047,  0.0107,  ...,  0.0267,  0.0331, -0.0124]],
       requires_grad=True)
Initial weights gradient :  tensor([[-0.0030, -0.0030, -0.0030,  ..., -0.0030, -0.0030, -0.0030],
        [ 0.0022,  0.0022,  0.0022,  ...,  0.0024,  0.0022,  0.0022],
        [ 0.0002,  0.0002,  0.0002,  ...,  0.0002,  0.0002,  0.0002],
        ...,
        [ 0.0014,  0.0014,  0.0014,  ...,  0.0014,  0.0014,  0.0014],
        [ 0.0021,  0.0021,  0.0021,  ...,  0.0022,  0.0021,  0.0021],
        [ 0.0038,  0.0038,  0.0038,  ...,  0.0038,  0.0038,  0.0038]])


In [58]:
optimizer.zero_grad()

In [59]:
print('Initial weights : ',model[0].weight)
print('Initial weights gradient : ',model[0].weight.grad)

Initial weights :  Parameter containing:
tensor([[ 0.0012,  0.0206, -0.0279,  ...,  0.0234,  0.0052,  0.0035],
        [-0.0209, -0.0161, -0.0116,  ..., -0.0215, -0.0071, -0.0311],
        [-0.0202,  0.0148, -0.0334,  ..., -0.0204,  0.0011,  0.0079],
        ...,
        [ 0.0011, -0.0302,  0.0078,  ..., -0.0044,  0.0029,  0.0293],
        [-0.0243, -0.0231, -0.0075,  ...,  0.0105, -0.0334, -0.0168],
        [ 0.0290,  0.0047,  0.0107,  ...,  0.0267,  0.0331, -0.0124]],
       requires_grad=True)
Initial weights gradient :  tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])


application qui repars depuis le debut

In [60]:
model = FMNIST()
criterion = nn.NLLLoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

num_epochs = 3

for i in range(num_epochs):
    cum_loss = 0

    for images, labels in trainloader:
        optimizer.zero_grad()
        output = model(images)
        loss = criterion(output, labels)
        loss.backward()
        optimizer.step()
        
        cum_loss += loss.item()
       
     
    print(f"Training loss: {cum_loss/len(trainloader)}")

Training loss: 1.0100424232513412
Training loss: 0.5585998177909648
Training loss: 0.4902866960906271
